---
title: "About"
---

I'm Jasmine Chu, a recent graduate from UCLA with a degree in Statistics & Data Science and minor in Film, Television, and Digital Media. My academic background allows me to approach problems from both analytical and creative perspectives, combining data science with storytelling to bring unique insights and solutions.

Currently, I am focused on applying my skills in data analysis and statistical modeling to real-world challenges. I am particularly interested in how data-driven insights can influence decision-making in the entertainment industry.

When I'm not immersed in my studies, I enjoy dancing, video editing, hiking, going to concerts, and exploring new destinations! \newline

<button onclick="window.open('https://drive.google.com/file/d/1sfTCFxE2ImvxeAPmfMAyVPpi8IhYRcYN/view?usp=sharing', '_blank')" type="button" class="btn btn-link">Resume</button> \newline

Contact me: <a href="mailto:jasminechu33@email.com">jasminechu33@email.com</a> \newline

Connect with me: <a href="https://www.linkedin.com/in/jasmine-chu03/" target="_blank">https://www.linkedin.com/in/jasmine-chu03/</a>
